### ISSUE TITLE
Post Love 1.2.1 on phpBB 3.3.5

### ISSUE THREAD

**Issue by spectrumcomputing** [satanasov/postlove#84]
Hello,

I recently upgraded our site from the end of life 3.2 branch to the 3.3 branch.  I disabled Post Love 1.2.1 before the upgrade.  This morning I tried enabling the extension on the upgraded site and get the error below.  Please could you advise?  Our users on the forum very much miss the extension.

Thanks

```
phpBB encountered an error building the container due to an installed extension. For this reason, all extensions have been temporarily disabled. Please try purging your forum cache. All extensions will automatically be re-enabled once the container error is resolved. If this error continues, please visit phpBB.com for support.


Exception: The file "/var/www/html/forums/ext/anavaro/postlove/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 7 (near "- @auth").

#0 /var/www/html/forums/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile()
#1 /var/www/html/forums/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load()
#2 /var/www/html/forums/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services()
#3 /var/www/html/forums/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load()
#4 /var/www/html/forums/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process()
#5 /var/www/html/forums/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process()
#6 /var/www/html/forums/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
#7 /var/www/html/forums/phpbb/di/container_builder.php(223): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /var/www/html/forums/common.php(115): phpbb\di\container_builder->get_container()
#9 /var/www/html/forums/adm/index.php(23): require('/var/www/html/f...')
#10 {main}
```

**Comment by stefandrissen** [comment]
Peter, you seem to be using an old version of post love? That yaml file was updated to quote the values two years ago.

**Comment by spectrumcomputing** [comment]
Hi Stefan,

Thanks for the reply.

In phpBB its showing as the latest version:

![PostLove3 2](https://user-images.githubusercontent.com/38283339/160279687-14514421-33a2-4429-a36c-7fe18a6caa35.png)

You click 'Re-check all versions' within phpBB and it shows green if its the latest.  

I will clone the GitHub repository and try again.

Cheers

**Comment by spectrumcomputing** [comment]
Cloned the Git repository and it seems (still testing to be working).  It will be good when the extension is on the phpBB list as current again, then I guess the update checker would work as expected. Thanks
